# Generated by Django 5.1.4 on 2025-03-26 04:27

import pyotp
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_userprofile_otp_secret'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='otp_secret',
            field=models.CharField(blank=True, default=pyotp.random_base32, max_length=64),
        ),
    ]
