# Generated by Django 5.1.4 on 2024-12-13 23:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coworking', '0003_coworkingspace_reservation_review_spaceimage_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='space',
        ),
        migrations.RemoveField(
            model_name='review',
            name='user',
        ),
        migrations.DeleteModel(
            name='Reservation',
        ),
        migrations.DeleteModel(
            name='Review',
        ),
    ]
