# Generated by Django 5.1.4 on 2025-01-12 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coworking', '0006_coworkingspace_latitude_coworkingspace_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coworkingspace',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='coworkingspace',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True),
        ),
    ]
