# Generated by Django 5.1.4 on 2025-01-12 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coworking', '0008_alter_coworkingspace_latitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coworkingspace',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=14, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='coworkingspace',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=14, max_digits=20, null=True),
        ),
    ]
