# Generated by Django 5.1.4 on 2024-12-26 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='reservation_type',
            field=models.CharField(choices=[('hour', 'Por hora'), ('day', 'Por día'), ('week', 'Por semana'), ('month', 'Por mes')], default='hour', max_length=10),
        ),
        migrations.AddField(
            model_name='reservation',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
            preserve_default=False,
        ),
    ]
