# Generated by Django 5.1.4 on 2025-01-02 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0002_reservation_reservation_type_reservation_total_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='payment_method',
            field=models.CharField(choices=[('credit_card', 'Tarjeta de Crédito/Débito'), ('cash', 'Efectivo'), ('bank_transfer', 'Transferencia Bancaria'), ('other', 'Otro')], default='credit_card', max_length=20),
        ),
    ]
