# Generated by Django 5.1.4 on 2025-01-12 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0004_reservation_payment_card'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='payment_method',
            field=models.CharField(choices=[('credit_card', 'Tarjeta de Crédito/Débito'), ('cash', 'Efectivo'), ('bank_transfer', 'Transferencia Bancaria')], default='cash', max_length=20),
        ),
    ]
